### ISSUE TITLE
intelligent protector user guide file

### ISSUE THREAD

**Issue by noelmcloughlin** [opensds/proposals#4]
Just a friendly note - the [**/docs/intelligent protecter user guide**](https://github.com/opensds/proposals/blob/master/intelligent-protector/doc/intelligent-protector_user_guide.pdf) is actually an INSTALL GUIDE.  The name is misleading.

**Comment by noelmcloughlin** [comment]
Or a DEVELOPERS GUIDE?

**Comment by yxdming** [comment]
@noelmcloughlin 
did u used  this project in product environment?

**Comment by noelmcloughlin** [comment]
No - it was mentioned in a Bi-weekly technical discussion meeting so I just reviewed the document.
